name: Songdo OkPOS

on:
  repository_dispatch:
    types: [run-songdo-okpos]  # 트리거 타입 정의
  workflow_dispatch:  # ← 수동으로도 실행할 수 있게 추가

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Decode and Save Service Account JSON
        env:
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > /tmp/keyfile.json

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          SONGDO_OK_POS_ID: ${{ secrets.SONGDO_OK_POS_ID }}
          SONGDO_OK_POS_PW: ${{ secrets.SONGDO_OK_POS_PW }}
        run: |
          python 1-songdo-ok-pos-auto.py
